version: '3'
services:
  photonizer:
    image: nginx:latest
    container_name: photonginx
    ports:
      - 80:80
      - 9001:9001
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/photon.conf:/etc/nginx/conf.d/default.conf
      - ./srv/photon:/srv/photon
    links:
      - photonfpm

  photonfpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: photonfpm
    volumes:
      - ./srv/photon:/srv/photon
      - ./fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./fpm/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
      - ./fpm/extensions/gmagick.so:/usr/local/lib/php/extensions/no-debug-non-zts-20170718/gmagick.so
      - ./bin/cwebp:/usr/local/bin/cwebp
      - ./bin/jpegoptim:/usr/local/bin/jpegoptim
      - ./bin/optipng:/usr/local/bin/optipng
      - ./bin/pngquant:/usr/local/bin/pngquant



